### ISSUE TITLE
"Error: 108003: Already login"

### ISSUE THREAD

**Issue by Aboe646** [zinen/node-red-contrib-huawei-router#3]
Hey, first of all, thanks for creating this node, it's awesome!
I use it in my camper van in combination with a B535-232 and it works great, except that a lot of times I get the error "Error: 108003: Already login".
After a while it works again without a problem.
I have an inject of 30 seconds triggering the node. Do I something wrong?

P.s.: Is there a way to get the carriers name out of the information?

**Comment by zinen** [comment]
I have seen this error before too. I see it when running this node very often. Its a limit due to the way [huawei-lte-api](https://www.npmjs.com/package/huawei-lte-api) login session works. 
I haven't been able to solve it but to limit request to 5 per 1 minute(estimated limit from memory).

Ps: Can't seem to reach http://blog.hsp.dk/php-api-huawei-e5180-router/ to see what info can be found inside the router. Neither did searching "carrier" on the github for [huawei-lte-api](https://www.npmjs.com/package/huawei-lte-api) or [huawei-router-api](https://github.com/ishan-marikar/dialog-router-api#readme) give any results. So i don't thing so.

**Comment by Aboe646** [comment]
I only request the info (use the node) once every half minute and still get that error. Sometimes 5 minutes in row, other times I don't get the error for 15 minutes.
I'm not really able to discern a pattern in it.

**Comment by zinen** [comment]
Should be fixed as of version 1.0.0 fd5666f. Note that this is a breaking change and you will have to modify your nodes after this update.
Please report back if this is working for you.
